# Generated by Django 4.0.6 on 2022-08-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='clientes',
        ),
    ]
