# Generated by Django 4.0.6 on 2022-08-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0002_productos_delete_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='modelo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
