# Generated by Django 4.0.6 on 2022-08-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0003_alter_productos_modelo_alter_productos_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('profesion', models.CharField(max_length=150)),
            ],
        ),
    ]
