# Generated by Django 4.0.6 on 2022-08-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPage', '0004_integrantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('dias', models.CharField(max_length=150)),
                ('horarios', models.CharField(max_length=150)),
            ],
        ),
    ]
