# Generated by Django 4.0.6 on 2022-09-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('emisor', models.CharField(max_length=150)),
                ('receptor', models.CharField(max_length=150)),
            ],
        ),
    ]
